# Generated by Django 3.1 on 2020-08-27 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFilesUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_file', models.FileField(default=False, upload_to=product.models.location_project_file, verbose_name='file')),
                ('taxo_file', models.FileField(default=False, upload_to=product.models.location_project_file, verbose_name='taxo-file')),
                ('name', models.CharField(default='Undefined', max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('project_name', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='Files_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_file', models.FileField(default=False, upload_to=product.models.location_file, verbose_name='file')),
                ('data_type', models.CharField(choices=[('csv', 'csv'), ('xlsx', 'xslsx'), ('xls', 'xls'), ('pdf', 'pdf'), ('txt', 'txt'), ('jpeg', 'jpeg'), ('jpg', 'jpg')], max_length=25)),
                ('name', models.CharField(default='Undefined', max_length=150)),
                ('favorite', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
